config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  resources :users
  resources :tags
  
  root to: "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :title, :body, presence: true

	acts_as_taggable
	
	belongs_to :user
	has_many :answers
	has_many :attachments, as: :attachmentable
	has_many :comments, as: :commentable

	accepts_nested_attributes_for :attachments

	default_scope -> { order :created_at }

	before_destroy :destroy_answers

	private

	def destroy_answers
     self.answers.delete_all   
    end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
  	@questions = Question.all
  	respond_with @questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
	before_action :load_question, only: [:show, :edit, :update, :destroy]  
  before_action :build_answer, only: :show
  before_action :set_user_language, only: [:index]

  respond_to :html, :json

  authorize_resource

  def index
    respond_with(@questions = Question.search(params[:search], :page => params[:page]))
  end

  def show
    respond_with @question
  end

  def new
   respond_with(@question = Question.new)
  end

  def edit
  end

  def create
	 @question = Question.new(question_params)
   
   @question.user = current_user

   if @question.save
    flash[:notice] = 'Your question successfully created.'
	  redirect_to @question
	 else
	  render :new
	 end

  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
	  respond_with(@question.destroy)	 
  end

  private

  def set_user_language
    I18n.locale = params[:language]
  end

  def load_question
	 @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
	 params.require(:question).permit(:title, :body, :tag_list, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    .answer id="answer-#{answer.id}"
      p= answer.body
      ul
        - answer.attachments.each do |a|
          li= link_to a.file.identifier, a.file.url
      .name
        = link_to User.find(answer.user_id).name, user_path(answer.user_id)
      .time
        = answer.created_at.strftime("%B %e, %Y at %I:%M")
      - if user_signed_in? && can?(:update, answer)
        p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= link_to 'Delete', answer_path(answer), class: 'delete-answer-link', data: { confirm: 'Are you sure?', method: :delete }
        p
          = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
            = f.label :body, "Answer"
            = f.text_area :body, class: 'form-control'
            = f.submit 'Save', class: 'btn btn-primary'
    .comments
      = render 'comments/list', parent: answer

app/views/questions/index.html.slim
- @questions.each do |question|
  p= link_to question.title, question
= will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/questions/new.html.slim
= nested_form_for @question do |f|
  - if I18n.locale == :ru
    p
      = f.label :title, "Заголовок вопроса"
    p
      = f.text_field :title, class: 'form-control'
    p
      = f.label :tag_list, "Теги для вопроса"
    p
      = f.text_field :tag_list, class: 'form-control'
    p
      = f.label :body, "Описание вопроса"
    p
      = f.text_area :body, class: 'form-control'
    p Прикрепить файлы:
    p
      = f.fields_for :attachments, @question.attachments.build do |a|
        = a.file_field :file
        = a.link_to_remove "Удалить этот файл"
      = f.link_to_add "Добавить", :attachments

    p= f.submit 'Создать вопрос', class: 'btn btn-primary'
  - else
    p
      = f.label :title, "Title of question"
    p
      = f.text_field :title, class: 'form-control'
    p
      = f.label :tag_list
    p
      = f.text_field :tag_list, class: 'form-control'
    p
      = f.label :body, "Description of question"
    p
      = f.text_area :body, class: 'form-control'
    p Attachments:
    p
      = f.fields_for :attachments, @question.attachments.build do |a|
        = a.file_field :file
        = a.link_to_remove "Remove this attachment"
      = f.link_to_add "Add", :attachments

    p= f.submit 'Create question', class: 'btn btn-primary'

app/views/questions/show.html.slim
.question
  h1= @question.title
  p= @question.body
  -if @question.attachments.count > 0
    p Attachments:
  ul
    - @question.attachments.each do |a|
      li= link_to a.file.identifier, a.file.url
  .name
    = link_to User.find(@question.user_id).name, user_path(@question.user_id)
  .time
    = @question.created_at.strftime("%B %e, %Y at %I:%M")
  .comments
    = render 'comments/list', parent: @question

.answers data={question_id: "#{@question.id}"}
  = render 'answers'

= form_for [@question, @answer], remote: true do |f|
  - if can?(:create, @answer)
    - if I18n.locale == :ru
      p
        = f.label :body, 'Ваш ответ'
        .answer-errors
        = f.text_area :body, class: 'form-control'
      p
        = f.fields_for :attachments, @answer.attachments.build do |a|
          = a.label :file
          = a.file_field :file
        p= f.submit 'Создать ответ', class: 'btn btn-primary'
    - else
      p
        = f.label :body, 'Your answer'
        .answer-errors
        = f.text_area :body, class: 'form-control'
      p
        = f.fields_for :attachments, @answer.attachments.build do |a|
          = a.label :file
          = a.file_field :file
        p= f.submit 'Create', class: 'btn btn-primary'

= subscribe_to "/questions/#{@question.id}/answers"