config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  resources :users
  resources :tags
  
  root to: "questions#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parent, except: :destroy
  before_action :load_comment, only: :destroy

  respond_to :js

  def create
    respond_with(@comment = @parent.comments.create(comment_params))
  end

  def destroy
    @comment.destroy
    redirect_to :back
  end

  private

  def load_parent
    @parent = Question.find(params[:question_id]) if params[:question_id]
    @parent ||= Answer.find(params[:answer_id])
  end

  def load_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/views/comments/_comment.html.slim
.comment
	= comment.body
	.dop
		- if can?(:destroy, comment)
			= link_to 'Delete', comment_path(comment), class: 'delete-answer-link', data: { confirm: 'Are you sure?', method: :delete }
		.name
			= link_to User.find(comment.user_id).name, user_path(comment.user_id)
		.time
			= comment.created_at.strftime("%B %e, %Y at %I:%M")

app/views/comments/_list.html.slim
= render parent.comments
- if can?(:create, parent.comments)
	=form_for [parent, parent.comments.build], remote: true do |f|
	  - if I18n.locale == :ru
		  p class="form-group"
		    = f.label :body, 'Коммент'
		    = f.text_area :body, class: 'form-control'
		  p
		    = f.submit 'Оставить комментарий', class: 'btn btn-primary'
	  - else
	  	  p class="form-group"
		    = f.label :body, 'Comment'
		    = f.text_area :body, class: 'form-control'
		  p
		    = f.submit 'Post comment', class: 'btn btn-primary'

app/views/comments/create.js.erb
var parentSelector = '<%= @parent.is_a?(Question) ? ".question" : "#answer-#{@parent.id}" %>';
console.log($(parentSelector + ' .comments'));
$(parentSelector).siblings('.comments').html('<%= j render "list", parent: @parent %>');