config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  resources :users
  resources :tags
  
  root to: "questions#index"

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Zqa"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          div= link_to t('name'), root_path, class: "navbar-brand"
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to t('questions'), questions_path
              li= link_to t('tags'), tags_path
              li= link_to t('users'), users_path
              - if can?(:create, Question)
                li= link_to t('ask'), new_question_path
              - if user_signed_in?
                li= link_to t('logout'), destroy_user_session_path, method: :delete
              - else
                li= link_to t('login'), new_user_session_path
              li
                = form_tag questions_path, method: :get, class: "form-search"
                  = text_field_tag 'search', nil, placeholder: t('search_cond')
                  button type="submit" class="btn" Search



    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield          
        .col-lg-3
          .well.sidebar-nav
            h3= t('languages')
            ul.nav.nav-list
              li.nav-header
              li= link_to t('rus'), questions_path(language: "ru")
              li= link_to t('eng'), questions_path(language: "en")

      footer
        .nav
          ul
            li= link_to t('about'),   "#"
            li= link_to t('contact'), "#"
            li= link_to t('news'), "http://weblog.rubyonrails.org/"
      / = debug(params) if Rails.env.development?